PS-3941: Skip Travis CI builds for commits without code changes

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,6 +11,7 @@ cache:
 
 env:
   global:
+    - PARENT_BRANCH=5.7
     - CCACHE_DIR=$HOME/.ccache
     - CCACHE_COMPRESS=1
     - CCACHE_COMPRESSLEVEL=9
@@ -25,7 +26,7 @@ matrix:
         - wget https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py
         - chmod a+x clang-format-diff.py
         - git diff -U0 --no-color HEAD^1 | ./clang-format-diff.py -p1 >_GIT_DIFF
-        - '[ ! -s _GIT_DIFF ] && echo The last git commit is clang-formatted || cat _GIT_DIFF'
+        - '[ ! -s _GIT_DIFF ] && { echo The last git commit is clang-formatted; travis_terminate 0; } || { cat _GIT_DIFF; travis_terminate 1; }'
 
 
     # Configurations for developers' forks and after merging a pull request for percona/percona-server
@@ -135,7 +136,7 @@ matrix:
 
 script:
   - JOB_NUMBER=$(echo $TRAVIS_JOB_NUMBER | sed -e 's:[0-9][0-9]*\.\(.*\):\1:');
-    echo --- JOB_NUMBER=$JOB_NUMBER PACKAGES=$PACKAGES TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
+    echo --- JOB_NUMBER=$JOB_NUMBER TRAVIS_COMMIT=$TRAVIS_COMMIT TRAVIS_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
 
   - echo --- Perform all Travis jobs or only jobs that are included in ENV_VAR_JOB_NUMBERS list if it is defined;
     JOB_NUMBERS="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24";
@@ -146,6 +147,26 @@ script:
     if [[ ! " ${JOB_ARRAY[@]} " =~ " ${JOB_NUMBER} " ]]; then
        echo --- Finishing as job ${JOB_NUMBER} is not on a list = $JOB_NUMBERS;
        travis_terminate 0; 
+    fi;
+
+  # For the trunk use TRAVIS_COMMIT_RANGE but "Auto cancel branch builds" has to be turned off at https://travis-ci.org/percona/percona-server/settings
+  # For pull requests and feature branches replace TRAVIS_COMMIT_RANGE with the range from the root to the tip of the branch
+  - if [[ "$TRAVIS_EVENT_TYPE" == "pull_request" ]] || [[ "$TRAVIS_REPO_SLUG" != "percona/percona-server" ]]; then
+      if [[ "$TRAVIS_EVENT_TYPE" == "pull_request" ]]; then TRAVIS_COMMIT=$TRAVIS_COMMIT^2; fi;
+      git fetch https://github.com/percona/percona-server.git $PARENT_BRANCH:master_repo_$PARENT_BRANCH;
+      PARENT_COMMIT=$(git rev-list --first-parent --topo-order $TRAVIS_COMMIT ^master_repo_$PARENT_BRANCH | tail -1);
+      TRAVIS_COMMIT_RANGE=$PARENT_COMMIT^..$TRAVIS_COMMIT;
+    fi;
+    if MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE 2>/dev/null); then
+      echo -e "--- Modified files in $TRAVIS_COMMIT_RANGE:\n$MODIFIED_FILES";
+      if ! echo "$MODIFIED_FILES" | grep -qvE '^(doc|build-ps|mysql-test|packaging|policy|scripts|support-files)/'; then
+        echo "--- There are no code changes, stopping build process.";
+        travis_terminate 0;
+      else
+        echo "--- Code changes were found";
+      fi;
+    else
+      echo "--- Can't prepare MODIFIED_FILES for $TRAVIS_COMMIT_RANGE";
     fi;
 
   - echo --- Configure required LLVM and Ubuntu Toolchain repositories;
@@ -193,7 +214,10 @@ script:
       -DWITH_PAM=ON
     ";
     if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
-      CMAKE_OPT+=" -DMYSQL_MAINTAINER_MODE=ON -DWITH_MECAB=system";
+      CMAKE_OPT+="
+        -DMYSQL_MAINTAINER_MODE=ON
+        -DWITH_MECAB=system
+      ";
       if [[ "$TRAVIS_REPO_SLUG" == "percona/percona-server" ]]; then
         CMAKE_OPT+=" -DWITH_TOKUDB=ON -DWITH_ROCKSDB=ON";
       else
@@ -205,7 +229,7 @@ script:
         fi;
       fi;
     else
-      CMAKE_OPT="$CMAKE_OPT
+      CMAKE_OPT+="
         -DMYSQL_MAINTAINER_MODE=OFF
         -DWITH_PROTOBUF=system
         -DWITH_TOKUDB=OFF
@@ -213,7 +237,7 @@ script:
       ";
     fi;
     if [[ "$INVERTED" == "ON" ]]; then
-      CMAKE_OPT="$CMAKE_OPT
+      CMAKE_OPT+="
         -DWITH_EMBEDDED_SERVER=OFF
         -DWITH_EDITLINE=bundled
         -DWITH_LIBEVENT=system
@@ -229,7 +253,7 @@ script:
         -DWITHOUT_PARTITION_STORAGE_ENGINE=ON
         -DWITHOUT_PERFSCHEMA_STORAGE_ENGINE=ON
       ";
-    fi; 
+    fi;
 
   - echo --- Perform Debug or RelWithDebInfo compilation;
     echo --- CMAKE_OPT=\"$CMAKE_OPT\";
@@ -237,6 +261,6 @@ script:
     cmake ..
       $CMAKE_OPT
       $ENV_VAR_CMAKE_OPT
-  - make -j2
+  - make -j2 || travis_terminate 1
   - ccache --show-stats
 
